
@startuml chess
' https://plantuml.com/class-diagram

skinparam style strictuml
skinparam ClassAttributeIconSize 0
skinparam ClassFontStyle bold

' constructeur à ajouter
' mouvement des pièces !!!
' aggrécation/composition -> nom des attributs
' type primaire exclusivement comeme attribut

package "model" {
    enum Color {
        WHITE
        BLACK
        - colorFrench : String {readOnly}
        Color(colorFrench : String)
        +getColorFrench()

    }

    class Position {
        - x: Integer {readOnly}
        - y: Integer {readOnly}
        + Position(x: Integer, y: Integer)
        + getPosition() : Integer[]
        + getRow() : Integer
        + getColumn()
        + getPiece() : Piece
        + setPiece(piece : Piece)
    }
    Position --* MoveObserver : <<use>>
    Position  --* "1" Piece : <<contains>>

    class Chessboard {
        - board : Position[]
        - capturedPiece : Piece[]
        + moveObservers : MoveObserver[]
        + Chessboard()
        + addCapturedPiece( piece : Piece)
        + getBoard() : Position[]
        + movePiece( from : Position, to : Position)
   }
    Chessboard *-- "64..64" Position : <<contains>>
    Chessboard *-- "0..22" Piece : <<contains>>

    package "piece" {
        class Piece {
            -points : Integer
            -letter : String
            + Piece()
            + getColor() : Color
            + getPoints() : Integer
            + getLetter() : String
            + setStrategy(piecestrategy: PieceStrategy)
            + getMovements(x : Integer, y : Integer) : Integer[]
        }
        Piece *-- "1" PieceStrategy : <<contains>>
        Piece *-- "1" Color : <<contains>>
        Piece o- "0..*" MoveObserver : <<observe>>


        interface PieceStrategy <<interface>> {
            + getPoints() : Integer
            + getLetter() : String
                        + getMovements(x : Integer, y : Integer) : Integer[]

        }

        class KingStrategy implements PieceStrategy{
            +getPoints() : Integer
            +getLetter() : String
            + getMovements(x : Integer, y : Integer) : Integer[]
        }
        class QueenStrategy implements PieceStrategy{
            +getPoints() : Integer
            +getLetter() : String
            + getMovements(x : Integer, y : Integer) : Integer[]
        }
        class RookStrategy implements PieceStrategy {
            +getPoints() : Integer
            +getLetter() : String
            + getMovements(x : Integer, y : Integer) : Integer[]
        }
        class BishopStrategy implements PieceStrategy{
            +getPoints() : Integer
            +getLetter() : String
            + getMovements(x : Integer, y : Integer) : Integer[]
        }
        class KnightStrategy implements PieceStrategy {
            +getPoints() : Integer
            +getLetter() : String
            + getMovements(x : Integer, y : Integer) : Integer[]
            - castling : Boolean
        }
        class PawnStrategy implements PieceStrategy{
            +getPoints() : Integer
            +getLetter() : String
            + getMovements(x : Integer, y : Integer) : Integer[]
        }

        class FactoryStrategy {
            + createKingStrategy(color: Color) : Piece
            + createQueenStrategy(color: Color) : Piece
            + createRookStrategy(color: Color) : Piece
            + createBishopStrategy(color: Color) : Piece
            + createKnightStrategy(color: Color) : Piece
            + createPawnStrategy(color: Color) : Piece
        }

        KingStrategy <.. FactoryStrategy : <<use>>
        QueenStrategy <.. FactoryStrategy : <<use>>
        RookStrategy <.. FactoryStrategy : <<use>>
        BishopStrategy <.. FactoryStrategy : <<use>>
        KnightStrategy <.. FactoryStrategy : <<use>>
        PawnStrategy <.. FactoryStrategy : <<use>>

        FactoryStrategy .> Piece : <<create>>
    }

    interface MoveObserver <<interface>> {
         + beforeMove(oldposition : Position, newposition : Position)
         + afterMove(oldposition : Position, newposition : Position)
    }

    Chessboard ..> FactoryStrategy : <<use>>

    class CaptureObserver implements MoveObserver{
            +CaptureObserver(chessboard : Chessboard)
            + beforeMove(oldposition : Position, newposition : Position)
            + afterMove(oldposition : Position, newposition : Position)
    }
    CaptureObserver --* Chessboard : <<contains>>

}


package "view" {
    class ChessboardView extends JFrame {
        + ChessboardView(party : Party)
        - createLabel( x : Integer, y : Integer ) : Jlabel
        + drawPosition( position : Position)
        - resetColor (label : Jlabel, x : Integer, y : Integer)
        + setColor ( position : Position, color : java.awt.Color)
        + getInstance() : ChessboardView
        - positionToIndex ( position : Position) : Integer
        - indexToLabel (index : Integer) : Jlabel
        - getLabel ( position : Position) : Jlabel
        + resetAllBackground()
        }

}

package "controller" {
    class ChessMain() {
        + {static} main()
    }
    class CheckObserver implements MoveObserver {
        + update(old: Position, new: Position)
    }
    class Party {
    +Party()
    +ClikOnCase(x : Integer, y : Integer)

    }

    Party --* "1" Chessboard: <<contains>>
    Party --* ChessboardView : <<use>>
    Party --* "2"Color : <<contains>>
    Party --* Position : <<use>>
}


@enduml
